### ISSUE TITLE
mac 下用不了？

### ISSUE THREAD

**Issue by frankbai-baiwei** [Math312/swagger-helper#14]
mac下无法使用，generate没有找到选项；另一台Windows机器可以用

**Comment by Math312** [comment]
请提供一下使用插件的版本号，作者本身就是使用mac开发的。请提供解析的部分代码，看是否可以复现

**Comment by frankbai-baiwei** [comment]
![image](https://user-images.githubusercontent.com/81797045/114831485-053cee80-9e00-11eb-854b-37c5d45ae5ce.png)

![image](https://user-images.githubusercontent.com/81797045/114831514-0c63fc80-9e00-11eb-95ff-b2dac443e406.png)
![image](https://user-images.githubusercontent.com/81797045/114831593-230a5380-9e00-11eb-8b7c-26b0836f3f00.png)

**Comment by Math312** [comment]
了解了，这可能是一个升级过程中造成的bug，我会尽快进行修复，感谢您指出该插件的问题

**Comment by Math312** [comment]
IDEA插件平台审核需要一段时间，如果急于使用，请从github中下载。

[链接地址](https://github.com/Math312/swagger-helper/releases/tag/0.5.2.1)
