### ISSUE TITLE
你好 请问有没有增加更多自定义配置的想法

### ISSUE THREAD

**Issue by itodouble** [Math312/swagger-helper#17]
例如 对于实体bean是否生成```required```

**Comment by Math312** [comment]
我需要查看一下这是否是swagger 2.0规范中的注解

**Comment by Math312** [comment]
我认为你所提到的注解，可能是Spring 中用于依赖注入的那个@Required注解

全限定类名是`org.springframework.beans.factory.annotation.Required`

我没有在Swagger 2.0规范中找到这个注解。

如果你需要在Swagger文档中标出是否需要填写该参数，可以尝试修改`ApiModel`和`ApiImplicitParam`注解中的内容

**Comment by Math312** [comment]
本工具旨在

`帮助开发者在生成API文档时更加方便，避免写更多的关于格式上的东西，只需要填写业务含义，以减少工作量`

对于开发文档以外的内容，不提供其他支持，如果您提到的功能是一个关于API文档的功能，请详细描述一下。

**Comment by itodouble** [comment]
这个
```
@ApiModelProperty(value = "id", required = true)
```

**Comment by Math312** [comment]
对的，可以使用这个指定，因为ApiImplicitParam注解用于指定body类型的Api文档会产生多层嵌套，会使开发者混乱，所以对于body类型的都是用ApiModel注解相关的注解描述文档的

**Comment by Math312** [comment]
感谢使用，如果有一些新的想法欢迎提出issue
