### ISSUE TITLE
0.5.2.1版本能支持idea社区版么？

### ISSUE THREAD

**Issue by javalover123** [Math312/swagger-helper#18]
[https://plugins.jetbrains.com/plugin/15314-swagger-helper/versions](https://plugins.jetbrains.com/plugin/15314-swagger-helper/versions)

![image](https://user-images.githubusercontent.com/9191388/119106175-a565e300-ba50-11eb-8366-1957583a29e6.png)

**Comment by Math312** [comment]
未来将会支持社区版，只不过会缺少一些功能，例如：解析Spring Context 进行响应码解析的功能，但是可能需要一些时间，因为我自身的时间问题
